# Generated by Django 3.1.1 on 2020-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
            ],
            options={
                'verbose_name': '人员信息',
                'db_table': 'allperson',
                'managed': False,
            },
        ),
    ]
