# Generated by Django 3.0.6 on 2020-06-11 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': '人员信息',
            },
        ),
        migrations.CreateModel(
            name='CertificateInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate', models.FileField(blank=True, upload_to='images/')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.PersonInfo')),
            ],
            options={
                'verbose_name': '证件信息',
            },
        ),
    ]
